RabbitMQ:
    HostName: localhost
    Port: 5672
    UserName: guest
    Password: guest
    Exchanges:
        - Name: membership-status-exchange
          Type: topic
          Durable: true
          AutoDelete: false
          Publishers:
              - MembershipStatusPublisher
        - Name: book-order-exchange
          Type: topic
          Durable: true
          AutoDelete: false
          Publishers:
              - BookOrderPublisher
    Queues:
        - Name: membership-status-queue
          Durable: true
          Exclusive: false
          AutoDelete: false
          Consumers:
              - MembershipStatusConsumer
        - Name: book-reservation-queue
          Durable: true
          Exclusive: false
          AutoDelete: false
          Consumers:
              - BookReservationConsumer
        - Name: book-provision-queue
          Durable: true
          Exclusive: false
          AutoDelete: false
          Consumers:
              - BookProvisionConsumer
    Bindings:
        - Queue: membership-status-queue
          Exchange: membership-status-exchange
          BindingKey: "membership.status.*"
        - Queue: book-reservation-queue
          Exchange: book-order-exchange
          BindingKey: "book.reservation.*"
        - Queue: book-provision-queue
          Exchange: book-order-exchange
          BindingKey: "book.provision.*"
        
